### ISSUE TITLE
a way to avoid blocking by role? or whitelist?

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ip_blocking#9] opened 2021-06-15 16:53 UTC
I'm having problems with this module when it blocks me when doing admin tasks. Wouldn't it be nice to have a way to avoid a blocking by role? Or just a whitelist of ips?

**Comment by findlabnet** [comment] 2021-06-15 17:40
Thanks for your input, can you describe the scenario in which this problem(s) occurred?
By design you cannot block your own IP.

**Comment by robertgarrigos** [comment] 2021-06-16 09:25
It's happening, sometimes, when uploading an image through a standard image field. The ajax call is triggering the block. I have to go to the database and delete the entry of my ip.

**Comment by findlabnet** [comment] 2021-06-16 09:42
Do you have the "Antiscan" module installed? If so, which of "Restricted path patterns" do you use?

**Comment by robertgarrigos** [comment] 2021-06-19 19:20
The default ones: user/ and admin/. I see, I could add the file/ajax/ one, isn't?

**Comment by findlabnet** [comment] 2021-06-20 06:01
If I understand correctly, you mean **"Not blockable path patterns"** in the **"Antiscan"** module.
You have the **"Test mode"** checkbox below in the module settings form, which gives you the ability to test any path pattern you want without self-blocking.
Anyway, in the next release of "Antiscan" module (few more days) I'll add check for current logged in user IP for this module too.
Let me know if you need any help.

**Comment by robertgarrigos** [comment] 2021-06-20 18:48
thanks @findlabnet

**Comment by robertgarrigos** [comment] 2021-06-23 09:43
However, I added the fiel/ajax/ path to that antiscan setting, and it's still blocking me, not always, though.

**Comment by findlabnet** [comment] 2021-06-23 10:11
If you try `file/*` as temporary solution?
In new version this will be fixed.

**Comment by findlabnet** [comment] 2021-06-27 18:44
Version 1.x-1.0.5 of [Antiscan](https://backdropcms.org/project/antiscan) module are available for now with notable additions.
Thanks again @robertgarrigos for testing, this issue can be closed.
If you have any further questions, please use the module issue queue at https://github.com/backdrop-contrib/antiscan/issues.

**Closed as completed** 2021-07-07 08:57 UTC

**Comment by robertgarrigos** [comment] 2021-07-11 16:39
Thanks @findlabnet
